language: python
python:
  - "2.7"
# command to install dependencies
script: python spatial_efd/tests/test.py
branches:
  only:
    - master
sudo: required
before_install:
 - chmod +x spatial_efd/tests/test.py
install:
 - pip install .
 - pip install -r travis.requirements.txt
