language: python
python:
  - "2.7"
script: python spatial_efd/tests/test.py
branches:
  only:
    - master
install:
 - pip install .
 - pip install -r .travis.requirements.txt
before_install:
 - pip install codecov
after_success:
 - codecov
