language: python
python:
  - "2.7"
script: coverage run --source spatial_efd setup.py test
branches:
  only:
    - master
install:
 - pip install .
 - pip install -r .travis.requirements.txt
before_install:
 - pip install codecov
after_success:
 - codecov
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start
